import Link from "next/link";

export const metadata = {
  title: "Terms & Conditions — ProBuddy",
  description:
    "Terms and conditions for using ProBuddy, the AI-powered home services marketplace.",
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 md:py-16">
      <h1 className="font-display text-3xl md:text-4xl font-extrabold tracking-tight text-on-surface">
        Terms &amp; Conditions
      </h1>
      <p className="text-sm text-on-surface-variant mt-2">
        Last updated: 23 February 2026
      </p>

      <div className="mt-8 space-y-8 text-on-surface-variant leading-relaxed">
        {/* 1 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using ProBuddy (&quot;probuddy.ai&quot;, the
            &quot;Service&quot;), you agree to be bound by these Terms &amp;
            Conditions. If you do not agree, please do not use the Service.
          </p>
        </section>

        {/* 2 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            2. Description of Service
          </h2>
          <p>
            ProBuddy is an AI-powered marketplace that helps homeowners find
            trusted local professionals for home services such as plumbing,
            electrical work, roofing, painting, and more. We aggregate
            professional listings from third-party providers (including
            Thumbtack) and use artificial intelligence to analyze profiles,
            reviews, and experience to rank and recommend professionals.
          </p>
          <p className="mt-3">
            ProBuddy is an information and referral service.{" "}
            <strong className="text-on-surface">
              We do not employ, endorse, or guarantee any professional listed on
              our platform.
            </strong>{" "}
            Any contract for services is between you and the professional
            directly.
          </p>
        </section>

        {/* 3 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            3. User Accounts
          </h2>
          <p>
            Browsing and searching ProBuddy does not require an account. If you
            choose to create an account (for example, to access the admin
            dashboard), you are responsible for maintaining the confidentiality
            of your credentials and for all activity under your account. You
            agree to provide accurate information and to notify us promptly of
            any unauthorized use.
          </p>
        </section>

        {/* 4 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            4. AI-Generated Content
          </h2>
          <p>
            ProBuddy uses artificial intelligence to generate rankings, chat
            responses, pricing estimates, tips, and other content. While we
            strive for accuracy, AI-generated content is{" "}
            <strong className="text-on-surface">
              provided for informational purposes only
            </strong>{" "}
            and should not be treated as professional advice.
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-1.5">
            <li>
              AI rankings are based on publicly available profile information and
              reviews and may not reflect the most current data.
            </li>
            <li>
              Pricing estimates are approximate and will vary based on location,
              scope, and materials.
            </li>
            <li>
              Chat responses are generated by AI and may occasionally contain
              inaccuracies.
            </li>
          </ul>
          <p className="mt-3">
            Always verify important details directly with the professional
            before hiring.
          </p>
        </section>

        {/* 5 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            5. Third-Party Services
          </h2>
          <p>
            ProBuddy integrates with third-party services to deliver its
            features:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-1.5">
            <li>
              <strong className="text-on-surface">Thumbtack</strong> — provides
              professional listings and search results.
            </li>
            <li>
              <strong className="text-on-surface">Google Gemini AI</strong> —
              powers AI chat, ranking analysis, and content generation.
            </li>
            <li>
              <strong className="text-on-surface">Cloudflare</strong> — provides
              hosting, security, and bot protection (Turnstile).
            </li>
            <li>
              <strong className="text-on-surface">Microsoft Clarity</strong> —
              provides analytics to improve the user experience.
            </li>
            <li>
              <strong className="text-on-surface">OpenStreetMap</strong> —
              provides map tiles for location features.
            </li>
          </ul>
          <p className="mt-3">
            Your use of ProBuddy is also subject to the terms and privacy
            policies of these third-party services.
          </p>
        </section>

        {/* 6 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            6. Acceptable Use
          </h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 mt-3 space-y-1.5">
            <li>
              Use the Service for any unlawful purpose or in violation of
              applicable laws.
            </li>
            <li>
              Attempt to scrape, crawl, or extract data from ProBuddy using
              automated tools without prior written consent.
            </li>
            <li>
              Interfere with or disrupt the Service, including bypassing
              security or bot-protection measures.
            </li>
            <li>
              Submit false, misleading, or fraudulent information through
              searches, chat, or forms.
            </li>
            <li>
              Abuse the AI chat or ranking features (for example, by submitting
              excessive or automated requests).
            </li>
          </ul>
        </section>

        {/* 7 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            7. Intellectual Property
          </h2>
          <p>
            All content, design, branding, and software on ProBuddy (excluding
            third-party data such as Thumbtack listings and OpenStreetMap tiles)
            is owned by or licensed to ProBuddy and is protected by intellectual
            property laws. You may not reproduce, distribute, or create
            derivative works without our prior written consent.
          </p>
        </section>

        {/* 8 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            8. Limitation of Liability
          </h2>
          <p>
            To the fullest extent permitted by law, ProBuddy and its operators
            shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages arising from your use of the
            Service, including but not limited to:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-1.5">
            <li>
              The quality, safety, or legality of services provided by
              professionals found through ProBuddy.
            </li>
            <li>
              Any inaccuracy in AI-generated content, rankings, or pricing
              estimates.
            </li>
            <li>
              Service interruptions, data loss, or technical issues.
            </li>
          </ul>
        </section>

        {/* 9 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            9. Disclaimer of Warranties
          </h2>
          <p>
            The Service is provided &quot;as is&quot; and &quot;as
            available&quot; without warranties of any kind, whether express or
            implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and
            non-infringement. We do not warrant that the Service will be
            uninterrupted, error-free, or that AI-generated content will be
            accurate or complete.
          </p>
        </section>

        {/* 10 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            10. Governing Law
          </h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of the State of Delaware, United States, without regard to
            conflict-of-law principles. Any disputes arising under these Terms
            shall be subject to the exclusive jurisdiction of the state and
            federal courts located in the State of Delaware.
          </p>
        </section>

        {/* 11 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            11. Changes to These Terms
          </h2>
          <p>
            We may update these Terms from time to time. When we do, we will
            revise the &quot;Last updated&quot; date at the top of this page.
            Continued use of the Service after changes are posted constitutes
            your acceptance of the revised Terms.
          </p>
        </section>

        {/* 12 */}
        <section>
          <h2 className="font-display text-xl font-bold text-on-surface mb-3">
            12. Contact Us
          </h2>
          <p>
            If you have questions about these Terms, please contact us at{" "}
            <a
              href="mailto:hello@probuddy.ai"
              className="text-primary hover:text-primary-hover underline"
            >
              hello@probuddy.ai
            </a>
            .
          </p>
        </section>

        {/* Cross-link */}
        <div className="pt-4 border-t border-outline-variant/50">
          <p className="text-sm">
            See also our{" "}
            <Link
              href="/privacy"
              className="text-primary hover:text-primary-hover underline"
            >
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </div>
    </div>
  );
}
