-- Backfill missing category descriptions
-- Run with: npx wrangler d1 execute find-a-pro-db --remote --file scripts/backfill-descriptions.sql

UPDATE categories SET description = 'Expert architectural design for renovations, extensions, and new builds.' WHERE slug = 'architect' AND description IS NULL;
UPDATE categories SET description = 'Smart home installation, automation, and whole-house technology integration.' WHERE slug = 'home-systems-specialist' AND description IS NULL;
UPDATE categories SET description = 'Tools and machinery for DIY projects, construction, and special events.' WHERE slug = 'equipment-rental-provider' AND description IS NULL;
UPDATE categories SET description = 'Pool and spa construction, maintenance, and repair services.' WHERE slug = 'pool-spa-specialist' AND description IS NULL;
UPDATE categories SET description = 'Skilled brickwork, stonework, and concrete for walls, patios, and foundations.' WHERE slug = 'mason' AND description IS NULL;
UPDATE categories SET description = 'Professional bookkeeping, tax preparation, and financial advisory services.' WHERE slug = 'accountant' AND description IS NULL;
UPDATE categories SET description = 'Licensed contractors to manage your renovation or construction project from start to finish.' WHERE slug = 'general-contractor' AND description IS NULL;
UPDATE categories SET description = 'Qualified instructors for a wide range of skills and hobbies.' WHERE slug = 'instructor' AND description IS NULL;
UPDATE categories SET description = 'Custom woodworking, cabinetry, trim, and structural carpentry.' WHERE slug = 'carpenter' AND description IS NULL;
UPDATE categories SET description = 'Strategic advice to help grow your business and improve operations.' WHERE slug = 'business-consultant' AND description IS NULL;
UPDATE categories SET description = 'Hardwood, tile, laminate, and vinyl flooring installation and repair.' WHERE slug = 'flooring-specialist' AND description IS NULL;
UPDATE categories SET description = 'Professional photography for events, portraits, real estate, and more.' WHERE slug = 'photographer' AND description IS NULL;
UPDATE categories SET description = 'Creative classes in painting, pottery, crafting, and other hands-on arts.' WHERE slug = 'arts-crafts-instructor' AND description IS NULL;
UPDATE categories SET description = 'Window replacement, door installation, and weatherproofing services.' WHERE slug = 'window-door-installer' AND description IS NULL;
UPDATE categories SET description = 'Massage therapy, acupuncture, nutrition coaching, and holistic health.' WHERE slug = 'wellness-specialist' AND description IS NULL;
UPDATE categories SET description = 'Live entertainment for parties, events, and special occasions.' WHERE slug = 'entertainer' AND description IS NULL;
UPDATE categories SET description = 'Garage door installation, repair, opener replacement, and maintenance.' WHERE slug = 'garage-door-technician' AND description IS NULL;
UPDATE categories SET description = 'Professional obedience training, behavior correction, and socialization for pets.' WHERE slug = 'animal-trainer' AND description IS NULL;
UPDATE categories SET description = 'Custom home theater setup, surround sound, and media room installation.' WHERE slug = 'home-theater-installer' AND description IS NULL;
UPDATE categories SET description = 'Trusted pet sitting, dog walking, and in-home pet care services.' WHERE slug = 'pet-caregiver' AND description IS NULL;
UPDATE categories SET description = 'Custom metal fabrication, structural welding, and repair services.' WHERE slug = 'welder' AND description IS NULL;
UPDATE categories SET description = 'One-on-one and group language lessons for all ages and skill levels.' WHERE slug = 'language-teacher' AND description IS NULL;
UPDATE categories SET description = 'Lawn care, garden design, hardscaping, and outdoor living spaces.' WHERE slug = 'landscaper' AND description IS NULL;
UPDATE categories SET description = 'Mold removal, water damage restoration, and environmental cleanup.' WHERE slug = 'remediation-specialist' AND description IS NULL;
UPDATE categories SET description = 'Energy healing, spiritual counseling, and holistic wellness practices.' WHERE slug = 'spiritual-healer' AND description IS NULL;
UPDATE categories SET description = 'Creative event styling, floral arrangements, and venue decoration.' WHERE slug = 'event-decorator' AND description IS NULL;
UPDATE categories SET description = 'Private music lessons for guitar, piano, vocals, drums, and more.' WHERE slug = 'music-teacher' AND description IS NULL;
UPDATE categories SET description = 'Professional bartending services for parties, weddings, and corporate events.' WHERE slug = 'bartender' AND description IS NULL;
UPDATE categories SET description = 'Coaching and instruction in tennis, golf, swimming, and other sports.' WHERE slug = 'sports-instructor' AND description IS NULL;
UPDATE categories SET description = 'Safe, effective removal of insects, rodents, and other pests from your home.' WHERE slug = 'pest-control-specialist' AND description IS NULL;
UPDATE categories SET description = 'Hair styling, skincare, makeup, and nail services for any occasion.' WHERE slug = 'beautician' AND description IS NULL;
UPDATE categories SET description = 'Custom catering for weddings, corporate events, and private parties.' WHERE slug = 'caterer' AND description IS NULL;
UPDATE categories SET description = 'Residential and commercial cleaning for a spotless, healthy space.' WHERE slug = 'cleaner' AND description IS NULL;
UPDATE categories SET description = 'Professional grooming, bathing, and styling for dogs and cats.' WHERE slug = 'pet-groomer' AND description IS NULL;
UPDATE categories SET description = 'Reliable local transportation, delivery, and logistics services.' WHERE slug = 'transportation-provider' AND description IS NULL;
UPDATE categories SET description = 'Computer repair, network setup, cybersecurity, and tech support.' WHERE slug = 'it-specialist' AND description IS NULL;
UPDATE categories SET description = 'Legal counsel for contracts, disputes, real estate, and family matters.' WHERE slug = 'attorney' AND description IS NULL;
UPDATE categories SET description = 'Professional DJs for weddings, parties, corporate events, and more.' WHERE slug = 'dj' AND description IS NULL;
UPDATE categories SET description = 'Specialized pet services including veterinary care and exotic animal handling.' WHERE slug = 'pet-specialist' AND description IS NULL;
UPDATE categories SET description = 'Digital marketing, SEO, branding, and advertising strategy for your business.' WHERE slug = 'marketing-consultant' AND description IS NULL;
UPDATE categories SET description = 'Full-service event coordination for weddings, corporate events, and celebrations.' WHERE slug = 'event-planner' AND description IS NULL;
UPDATE categories SET description = 'Waitstaff, setup crews, and event support for any size gathering.' WHERE slug = 'event-staff-provider' AND description IS NULL;
UPDATE categories SET description = 'Personal coaching for career growth, relationships, and life transitions.' WHERE slug = 'life-coach' AND description IS NULL;
UPDATE categories SET description = 'Pressure washing, gutter cleaning, and exterior surface cleaning.' WHERE slug = 'outdoor-cleaner' AND description IS NULL;
UPDATE categories SET description = 'Local and long-distance moving, packing, and storage solutions.' WHERE slug = 'mover' AND description IS NULL;
UPDATE categories SET description = 'Routine home upkeep, seasonal maintenance, and preventive repairs.' WHERE slug = 'home-maintenance-specialist' AND description IS NULL;
UPDATE categories SET description = 'Logos, branding, marketing materials, and visual design for your business.' WHERE slug = 'graphic-designer' AND description IS NULL;
UPDATE categories SET description = 'Personal training, group classes, and fitness programs for all levels.' WHERE slug = 'fitness-instructor' AND description IS NULL;
UPDATE categories SET description = 'Thorough property inspections for buyers, sellers, and homeowners.' WHERE slug = 'home-inspector' AND description IS NULL;
UPDATE categories SET description = 'Alarm systems, surveillance cameras, and home security installation.' WHERE slug = 'security-specialist' AND description IS NULL;
UPDATE categories SET description = 'Creative interior design, space planning, and home staging services.' WHERE slug = 'interior-designer' AND description IS NULL;
UPDATE categories SET description = 'One-on-one academic tutoring for all subjects and grade levels.' WHERE slug = 'tutor' AND description IS NULL;
UPDATE categories SET description = 'Security assessments, risk analysis, and safety planning for homes and businesses.' WHERE slug = 'security-consultant' AND description IS NULL;
UPDATE categories SET description = 'Expert guidance for buying, selling, and investing in property.' WHERE slug = 'real-estate-professional' AND description IS NULL;
UPDATE categories SET description = 'Custom website design, development, and maintenance for businesses.' WHERE slug = 'web-developer' AND description IS NULL;
UPDATE categories SET description = 'SAT, ACT, GRE, and professional exam preparation with proven strategies.' WHERE slug = 'test-prep-tutor' AND description IS NULL;
UPDATE categories SET description = 'Document translation and interpretation services for any language pair.' WHERE slug = 'translator' AND description IS NULL;
